name: "更新插件版本"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-plugin-version:
    name: "更新插件版本"
    runs-on: ubuntu-latest
    steps:
      - name: "拉取代码"
        uses: actions/checkout@v6

      - name: "配置 PHP 环境"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: composer

      - name: "设置当前日期环境变量"
        run: |
          set -eo pipefail

          # 获取当前北京时间
          echo "CURRENT_DATE=$(TZ=Asia/Shanghai date +'%Y.%m.%d')" >> $GITHUB_ENV

          # 获取当前 aws/aws-sdk-php 包的版本
          echo "AWS_SDK_VERSION_BEFORE=$(composer show aws/aws-sdk-php | grep versions | awk '{print $NF}')" >> $GITHUB_ENV

          # 更新依赖包
          composer update --no-dev --prefer-dist --no-progress --no-interaction

          # 更新插件版本号
          sed -i "s/Version: .*/Version: ${{ env.CURRENT_DATE }}/" kratos-plugin-aws.php

          # 获取更新后的 aws/aws-sdk-php 包的版本
          echo "AWS_SDK_VERSION_AFTER=$(composer show aws/aws-sdk-php | grep versions | awk '{print $NF}')" >> $GITHUB_ENV

          # 比较 aws/aws-sdk-php 包的版本是否改变
          if [[ "${{ env.AWS_SDK_VERSION_BEFORE }}" == "${{ env.AWS_SDK_VERSION_AFTER }}" ]]; then
            echo "aws/aws-sdk-php 包的版本未改变，终止操作。"
            exit 1
          fi

      - name: "提交并推送变更"
        uses: actions-js/push@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          author_name: "github-actions[bot]"
          coauthor_email: "hi@seatonjiang.com"
          coauthor_name: "Seaton Jiang"
          message: "feat: update of plugin version"

      - name: "生成变更日志"
        run: |
          echo "### 变更日志" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "- 🚀 升级依赖包 \`aws/aws-sdk-php\` 的版本到 \`${{ env.AWS_SDK_VERSION_AFTER }}\`" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "- ✨ 升级插件版本到 \`${{ env.CURRENT_DATE }}\`" >> ${{ github.workspace }}-CHANGELOG.txt

      - name: "准备发布文件"
        run: |
          rm -rf dist
          mkdir -p dist
          cp kratos-plugin-aws.php dist/
          cp LICENSE dist/ || true
          rsync -a vendor/ dist/vendor/ --exclude 'bin/*' --delete

      - name: "创建 zip 文件"
        run: cd dist && zip -rq ../${{ env.CURRENT_DATE }}.zip . -x ".*" "*.zip"

      - name: "创建 Release"
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.CURRENT_DATE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/${{ env.CURRENT_DATE }}.zip
